### ISSUE TITLE
Don't return password in results

### ISSUE THREAD

**Issue by blainesch** [jnstr/zazu-password#2]
Since you are returning the password in the results it's stored in the zazu log files `~/.zazu/log`.

To get around this imagine a workflow like:

"password strong 32" -> "prefix script" that doesn't generate the password but passes "strong 32" to the next block.

The next block "copy" is a [user script](http://zazuapp.org/documentation/blocks/#user-script) which takes in "strong 32" as `value` from the previous block, it generate the password and copies it to the clipboard using the [clipboard](http://zazuapp.org/documentation/plugins/#clipboard) from the `pluginContext`.

Now Zazu never handles the secure password, but it's kept within the plugin making it more secure.

**Comment by jnstr** [comment]
You have a valid point there. Thanks!

I'll look into this when I have some spare time.

**Comment by jnstr** [comment]
@blainesch The first block renders the password query (e.g. "strong 32") instead of the password, which means that we don't have a password to show in the result. This means that the user doesn't see the generated password he's about to copy.

Could this be solved in a way?

**Comment by blainesch** [comment]
Correct, if you display it in Zazu it'll store it in the log file.

Is there a reason to display it? Maybe you could show what possible letters could be in it?
